export const defaultTheme = {
  colors: {
    primaryColor: "#048ABF",
    primaryColorAlt: "#036E9B",
    primaryColorLighter: "#05A3D4",
    titleColor: "#F2F2F2",
    textColor: "#6D6A7C",
    textLighter: "#A19FAD",
    inputColor: "#F2F2F2",
    bodyColor: "hsl(0, 0%, 12%)",
    containerColor: "hsl(0, 0%, 10%)",
    white: "#fff",
    concluded: "#66dbb9",
    inProgress: "#f8fc96",
  },
  fontSizes: {
    biggest: "2.5rem",  
    bigger: "1.75rem",   
    h1: "2rem",          
    h2: "1.5rem",       
    h3: "1.25rem",       
    normal: "1.2rem",      
    small: "0.875rem",   
    smaller: "0.75rem",  
    headerHeight: "4rem", 
},
  fontWeights: {
    regular: 400,
    medium: 500,
    semiBold: 600,
  },
};
